### ISSUE TITLE
don't use a different copy of esprima

### ISSUE THREAD

**Issue by jonathanong** [benjamn/es7-async-await#1]
this won't work if we want to combine it with other recast trasnforms. can you merge it into `esprima-fb` or something? don't feel like recasting multiple times...

**Comment by benjamn** [comment]
Yeah, using https://github.com/benjamn/esprima/tree/async-await is only temporary (until that gets merged into `esprima-fb`, soon), since it's still the only fork of Esprima (that I know of) that parses `async` functions right now.
